"""
The one definition of Animal Passport 0.1. tools/build.py generates the specification's field
tables and the JSON Schema from it, so the two cannot drift apart: change the format here (or the
prose in spec-template.md), never in the generated files.

A field is (name, type, description); a name ending in '*' is required. Every definition not in
NOT_RECORDS is a record, and also gets originRef (required), recordedAt, audit and extensions.

Types:
  string, text (HTML or plain), date, dateTime, decimal (decimal text), integer, boolean,
  bool? (true / false / null), amount, rate, range, rating, facility, ref, refs, files,
  strings, people, animals, population, token:a|b|c, obj:Def, arr:Def, schedule,
  doseDuration, drug, sha256, uuid
"""

COMMON = [
    ('originRef*', 'string', 'The record\'s identity in the system that first recorded it. Opaque: compare it for equality, never parse it. See [originRef](#originref).'),
    ('recordedAt', 'facility', 'Where the record was made, when that is not the exporting holder. See [recordedAt](#recordedat).'),
    ('audit', 'audit', 'When the record was created and by whom. See [audit](#audit).'),
    ('extensions', 'extensions', 'Values only the writing system understands. See [extensions](#extensions).'),
]

DEFS = {
    # ---- envelope ----
    'Manifest': ('The manifest: what the file is, who wrote it and what it contains.', [
        ('specVersion*', 'token:0.1', 'The version of this specification the file follows.'),
        ('transferBatchKey*', 'uuid', 'A UUID identifying this package. A reader can use it to refuse importing the same package twice.'),
        ('exportedDateTime*', 'dateTime', 'When the package was written.'),
        ('exportedBy', 'string', 'The person who exported it, as the source system writes the name.'),
        ('originSoftware*', 'obj:Software', 'The system that wrote the file.'),
        ('holderFacility', 'facility', 'The facility holding the animal when the passport was written. Expected; absent only when the source does not know it.'),
        ('ownerFacility', 'facility', 'The animal\'s owner, when known.'),
        ('contents*', 'arr:ContentsRow', 'One row for every record type the file carries, and for every type the sender chose to share even when it has no records. A record type the sender did not share is absent.'),
    ]),
    'Software': ('', [
        ('name*', 'string', 'The software\'s name.'),
        ('version', 'string', 'Its version.'),
    ]),
    'ContentsRow': ('', [
        ('recordType*', 'string', 'The key under `records`, for example `prescriptions`.'),
        ('recordCount*', 'integer', 'How many records of that type the file carries. For a grouped type (`measurements`, `enrichment`, `training`) it counts the `records`, not the configuration beside them. 0 means the type was shared and the animal has none.'),
    ]),
    'Core': ('Who the animal is. Always present.', [
        ('gan', 'string', 'The animal\'s Global Accession Number, when it has one. At least one of `localId` and `gan` is required.'),
        ('localId', 'string', 'The holder\'s local identifier for the animal. At least one of `localId` and `gan` is required.'),
        ('taxonomy*', 'obj:Taxonomy', 'What the animal is.'),
        ('currentSex', 'string', 'The current sex, as the source writes it (for example `Female`).'),
        ('birth', 'obj:Birth', 'Birth or hatch.'),
        ('animalType', 'token:individual|group|colony', 'Whether the record is one animal, a group or a colony.'),
        ('lifeCycle', 'obj:LifeCycle', 'Life-cycle state.'),
        ('population', 'population', 'The current count as males.females.unknown: for an individual `1.0.0`, `0.1.0` or `0.0.1`; for a group or colony, its members.'),
    ]),
    'Taxonomy': ('', [
        ('common', 'string', 'The common name.'),
        ('scientificName*', 'string', 'The scientific name.'),
        ('rank', 'string', 'The taxonomic rank of that name (for example `Species`, `Subspecies`).'),
        ('taxonIds', 'arr:TaxonId', 'Identifiers in public taxonomic databases.'),
    ]),
    'TaxonId': ('', [
        ('scheme*', 'string', 'The database: `itis` or `gbif`. Other public schemes may be added in later versions.'),
        ('value*', 'string', 'The identifier in that database.'),
    ]),
    'Birth': ('', [
        ('birthDate', 'date', 'The best single date of birth or hatch.'),
        ('birthDateEarliest', 'date|null', 'The earliest the date can be. Equal to `birthDate` when the date is exact; `null` when there is no lower bound.'),
        ('birthDateLatest', 'date|null', 'The latest the date can be; `null` when there is no upper bound.'),
        ('birthType', 'string', 'For example `Captive born`, `Wild born`.'),
        ('hybrid', 'string', 'Hybrid status, as the source writes it.'),
        ('birthInstitution', 'facility', 'Where the animal was born or hatched.'),
    ]),
    'LifeCycle': ('', [
        ('current', 'string', '`live`, `preBirth` or `dead`. A value outside these is shipped as the source holds it.'),
        ('initial', 'string', 'The state the record began in, with the same values.'),
    ]),

    # ---- identity ----
    'SexRecord': ('A dated determination of the animal\'s sex.', [
        ('recordDateTime', 'dateTime', 'When the sex was determined or recorded.'),
        ('sex*', 'string', 'The sex, as the source writes it.'),
        ('comments', 'string', ''),
    ]),
    'Identifier': ('A name, tag, transponder or other identifier.', [
        ('primary', 'boolean', '`true` on the animal\'s primary identifier, which is always shipped and listed first. Absent on the others.'),
        ('identifierType', 'string', 'For example `House Name`, `Transponder`, `Flipper Tag`.'),
        ('value*', 'string', 'The identifier itself.'),
        ('location', 'string', 'Where on the animal it is, for a physical identifier.'),
        ('recordDateTime', 'dateTime', 'When it was applied or recorded.'),
        ('removalDateTime', 'dateTime', 'When it was removed. An identifier with a removal date is no longer current.'),
        ('removalComments', 'string', ''),
        ('comments', 'string', ''),
        ('media', 'files', 'Photographs of the identifier. On the primary identifier, the identification photo.'),
    ]),
    'Parent': ('A parent of the animal.', [
        ('parentType', 'string', 'For example `Dam`, `Sire`.'),
        ('probability', 'decimal', 'The probability of parentage, 0 to 1, when the source records one.'),
        ('unknownReason', 'token:undetermined|wild', 'Why the parent is unknown: `wild` for a wild parent, `undetermined` otherwise. Present only when the parent is not identified.'),
        ('ids', 'arr:ParentId', 'The parent\'s identifiers, each with the facility it applies at.'),
        ('birthDate', 'date', 'The parent\'s date of birth.'),
        ('taxon', 'string', 'The parent\'s scientific name.'),
        ('comments', 'string', ''),
    ]),
    'ParentId': ('', [
        ('scheme*', 'token:local|gan', '`local` for a facility\'s local identifier, `gan` for a Global Accession Number.'),
        ('role', 'token:source|holder|owner', '`source`: the identifier at the exporting facility; `holder` or `owner`: at the parent\'s holder or owner.'),
        ('facility', 'facility', 'The facility the identifier belongs to.'),
        ('value*', 'string', 'The identifier.'),
    ]),
    'Rearing': ('How the animal was reared.', [
        ('recordDateTime', 'dateTime', ''),
        ('rearingType*', 'string', 'For example `Hand`, `Parent`.'),
        ('comments', 'string', ''),
    ]),
    'PopulationRecord': ('A count by life stage, for a group or colony. Derived at the source, so it carries no `originRef`.', [
        ('lifeStage', 'string', 'For example `Adult`, `Juvenile`.'),
        ('population*', 'population', 'The count as males.females.unknown.'),
        ('extensions', 'extensions', ''),
    ]),

    # ---- transactions ----
    'Transaction': ('An acquisition, disposition, move, birth, death or other transaction, with the holder and owner after it.', [
        ('recordDateTime', 'dateTime', 'When the transaction took place.'),
        ('transactionType*', 'obj:TransactionType', 'What kind of transaction it was.'),
        ('enclosureName', 'string', 'The enclosure involved, by name.'),
        ('population', 'arr:TransactionPopulation', 'The animals the transaction involves, by life stage. See TransactionPopulation.'),
        ('ownerAfterTransaction', 'facility', 'The owner after the transaction.'),
        ('holderAfterTransaction', 'facility', 'The holder after the transaction.'),
        ('geo', 'obj:Geo', 'Where it happened, for a transaction outside a facility such as a wild capture or stranding.'),
        ('death', 'obj:Death', 'Death details, on a death.'),
        ('rescue', 'obj:Rescue', 'Rescue and stranding details.'),
        ('comments', 'string', ''),
    ]),
    'TransactionType': ('', [
        ('description*', 'string', 'The transaction type as the source names it (for example `Move Animal`, `Death`).'),
        ('category', 'string', 'The broad category the type belongs to (for example `Acquisition`, `Disposition`, `Death`, `Move Animal`), so a reader can act on types it does not recognize.'),
    ]),
    'TransactionPopulation': ('The animals a transaction involves in one life stage, as males.females.unknown: for a death or a move, how many; for a life-stage change, the change in each stage, so a count may be negative (`0.-1.0` in one stage and `0.1.0` in the next).', [
        ('lifeStage', 'string', ''),
        ('population*', 'populationChange', ''),
    ]),
    'Geo': ('', [
        ('description', 'string', 'The place, described.'),
        ('city', 'string', ''), ('county', 'string', ''), ('state', 'string', ''), ('country', 'string', ''),
        ('bodyOfWater', 'string', ''),
        ('latitude', 'decimal', 'Decimal degrees.'),
        ('longitude', 'decimal', 'Decimal degrees.'),
        ('latLonType', 'string', 'How the position was taken, for example `GPS`.'),
        ('latLonEstimated', 'bool?', ''),
        ('depth', 'amount', ''),
        ('airTemperature', 'amount', ''),
        ('waterTemperature', 'amount', ''),
        ('weather', 'string', ''),
    ]),
    'Death': ('', [
        ('submittedDateTime', 'dateTime', 'When the death record was submitted.'),
        ('submittedBy', 'string', ''),
        ('history', 'string', 'The clinical history leading to the death.'),
        ('carcassCondition', 'string', ''),
        ('deathType', 'string', 'For example `Euthanasia`, `Found dead`.'),
        ('euthanasiaMethod', 'string', ''),
        ('ageAtDeathDays', 'decimal', 'Age at death in days, as the source recorded it.'),
        ('ageCategory', 'string', ''),
        ('inZooSinceDate', 'date', 'When the animal arrived at the facility where it died.'),
        ('acquisitionTransactionRef', 'ref', 'The `originRef` of the transaction by which that facility acquired the animal.'),
        ('acquisitionInstitution', 'facility', 'The facility it was acquired from.'),
        ('environmentNote', 'string', ''),
        ('exhibitStatus', 'string', ''),
        ('medicalStatus', 'string', ''),
        ('deathCode', 'string', 'The source\'s own death code.'),
    ]),
    'Rescue': ('Details of a rescue or stranding response. They can include the name, telephone and address of a member of the public; a sender should share them only where that is appropriate.', [
        ('eventConfirmed', 'bool?', 'Whether the stranding or rescue was confirmed.'),
        ('confirmation', 'string', ''),
        ('observerName', 'string', ''), ('observerPhone', 'string', ''), ('observerAddress', 'string', ''),
        ('reportDate', 'date', ''),
        ('animalConditionAtReport', 'string', ''), ('weatherConditionAtReport', 'string', ''),
        ('animalConditionAtRescue', 'string', ''),
        ('fisheryInteraction', 'string', ''), ('fisheryInteractionDetails', 'string', ''),
        ('boatStrike', 'string', ''), ('boatStrikeDetails', 'string', ''),
        ('humanInteraction', 'string', ''), ('humanInteractionDetails', 'string', ''),
        ('gearList', 'string', ''), ('gearDescriptionList', 'string', ''),
        ('potGear', 'string', ''), ('gillnetGear', 'string', ''), ('otherGear', 'string', ''),
        ('line1Diameter', 'amount', ''), ('line1DiameterEstimated', 'bool?', ''), ('line1Type', 'string', ''), ('line1Color', 'string', ''),
        ('line2Diameter', 'amount', ''), ('line2DiameterEstimated', 'bool?', ''), ('line2Type', 'string', ''), ('line2Color', 'string', ''),
        ('line3Diameter', 'amount', ''), ('line3DiameterEstimated', 'bool?', ''), ('line3Type', 'string', ''), ('line3Color', 'string', ''),
        ('floatBuoys', 'string', ''), ('buoyPotId', 'string', ''),
        ('gearCollected', 'bool?', ''), ('gearCollectedDetails', 'string', ''),
        ('gearRemoved', 'bool?', ''), ('gearRemovedDetails', 'string', ''),
        ('typeOfHook', 'string', ''), ('locationOfHook', 'string', ''),
        ('lineAttached', 'bool?', ''), ('leaderLineAttached', 'bool?', ''),
        ('surgeryNecessary', 'bool?', ''),
        ('causeOfStranding', 'string', ''), ('strandingType', 'string', ''), ('ageCategory', 'string', ''),
    ]),

    # ---- notes ----
    'AnimalNote': ('A general note about the animal.', [
        ('recordDateTime', 'dateTime', ''),
        ('category', 'string', 'The note\'s category, as the source names it.'),
        ('noteText*', 'text', 'The note. See [Text](#text).'),
        ('animals', 'animals', ''),
    ]),
    'ClinicalNote': ('A veterinary note.', [
        ('recordDateTime', 'dateTime', ''),
        ('category', 'string', ''),
        ('caseRef', 'ref', 'The `originRef` of the case the note belongs to, when it belongs to one.'),
        ('noteText*', 'text', 'The note. Records embedded in a note travel inside it; see [Text](#text).'),
        ('animals', 'animals', ''),
    ]),
    'NutritionNote': ('A nutrition note.', [
        ('recordDateTime', 'dateTime', ''),
        ('category', 'string', ''),
        ('noteText*', 'text', ''),
        ('animals', 'animals', ''),
    ]),

    # ---- medical ----
    'Case': ('A veterinary case.', [
        ('caseNumber', 'string', 'The source\'s case number.'),
        ('caseYear', 'string', 'The year the case number belongs to.'),
        ('caseType', 'string', 'For example `Clinical`, `Preshipment`.'),
        ('status', 'token:open|closed', 'An open case is still being worked at the sending facility.'),
        ('openedDateTime', 'dateTime', ''),
        ('closedDateTime', 'dateTime', ''),
        ('primaryVet', 'string', ''),
        ('complaint', 'string', ''),
        ('workingDiagnosis', 'string', ''),
        ('finalDiagnosis', 'strings', 'The final diagnoses.'),
        ('finalDiagnosisText', 'string', 'Free-text final diagnosis.'),
        ('animals', 'animals', ''),
    ]),
    'MedicalAlert': ('A medical alert for people working with the animal.', [
        ('recordDateTime', 'dateTime', 'When the alert was created.'),
        ('alertLevel', 'string', 'For example `Extreme`, `High`, `Medium`, `Low`.'),
        ('alertText*', 'string', ''),
        ('closedDateTime', 'dateTime', 'When the alert was closed. An alert without one is open.'),
        ('animals', 'animals', ''),
    ]),
    'ChronicCondition': ('A long-term condition and its reviews.', [
        ('recordDateTime', 'dateTime', 'When the condition was recorded.'),
        ('condition', 'string', 'The condition. Expected, though some sources hold conditions recorded without a name.'),
        ('status', 'string', 'For example `Active`, `Closed`, `Unmonitored`.'),
        ('detailedDescription', 'string', ''),
        ('reviews', 'arr:ConditionReview', ''),
    ]),
    'ConditionReview': ('', [
        ('reviewDateTime', 'dateTime', ''),
        ('rating', 'rating', 'How the condition was judged at the review, for example better, same or worse.'),
        ('comments', 'string', ''),
        ('action', 'string', 'What was decided.'),
    ]),
    'DrugReaction': ('An adverse reaction to a drug.', [
        ('recordDateTime', 'dateTime', 'When the reaction was recorded.'),
        ('drug*', 'drug', ''),
        ('reactionLevel', 'string', 'For example `Mild`, `Severe`, `Fatal`.'),
        ('comments', 'string', ''),
        ('animals', 'animals', ''),
    ]),
    'Prescription': ('A prescription and its doses.', [
        ('status', 'token:prescribed|dispensed|closed', '`prescribed`: written and not yet dispensed; `dispensed`: being given; `closed`: ended.'),
        ('recordDateTime', 'dateTime', 'When it was prescribed.'),
        ('treatmentStartDate', 'date', 'When treatment starts.'),
        ('treatmentEndDate', 'date', 'When treatment ends, if it has an end.'),
        ('prescribedBy', 'string', ''),
        ('route', 'string', 'For example `orally`, `ophthalmic`.'),
        ('instructions', 'string', ''),
        ('deliveryComments', 'string', ''),
        ('anesthesiaRef', 'ref', 'The `originRef` of the anesthesia the prescription belongs to, when it does.'),
        ('drugUse', 'arr:DrugUse', 'The drugs prescribed.'),
        ('animals', 'animals', ''),
    ]),
    'DrugUse': ('One drug within a prescription or an anesthetic, and its doses.', [
        ('drug', 'drug', 'The drug, when the source names one.'),
        ('prescriptionType', 'string', 'For example `Supplement`, `Preventive`.'),
        ('anestheticType', 'string', 'Within an anesthetic, for example `Preanesthetic`.'),
        ('doses', 'arr:Dose', ''),
    ]),
    'Drug': ('A drug. Not a record, so it carries no `originRef`.', [
        ('name', 'string', 'The drug\'s full name as the source writes it. At least one of `name`, `genericName` and `shortName` is present.'),
        ('shortName', 'string', ''),
        ('genericName', 'string', ''),
        ('concentration', 'obj:Concentration', ''),
    ]),
    'Concentration': ('', [
        ('value', 'decimal', 'The amount of drug in one unit of the delivery form.'),
        ('unit', 'string', 'The unit of that amount (UCUM where known).'),
        ('description', 'string', 'The concentration as the source describes it, for example `100 mg tablet`.'),
        ('deliveryForm', 'string', 'The form the drug is given in, for example `Tablet`, `mL`.'),
    ]),
    'Dose': ('', [
        ('doseRate', 'rate', 'The dose per unit of body weight, for example 5 mg per kg.'),
        ('drugAmount', 'amount', 'The amount of drug in one dose.'),
        ('dose', 'amount', 'The dose in the delivery form, for example 1 Tablet. Its unit is the delivery form as the source writes it, which in 0.1 is not necessarily a UCUM unit.'),
        ('administration', 'token:apply|give', '`apply` for a topical application, `give` otherwise. Absent when unknown.'),
        ('frequency', 'schedule', 'How often the dose is given.'),
        ('duration', 'doseDuration', 'How long it continues.'),
    ]),
    'Anesthesia': ('An anesthesia or immobilization event.', [
        ('number', 'string', 'The source\'s anesthesia number.'),
        ('year', 'string', ''),
        ('recordDateTime', 'dateTime', ''),
        ('reason', 'string', ''),
        ('anesthetist', 'string', ''), ('primaryVet', 'string', ''), ('recorder', 'string', ''),
        ('health', 'string', ''), ('physicalStatus', 'string', 'For example an ASA-style class.'),
        ('activityLevel', 'string', ''), ('demeanor', 'string', ''), ('bodyCondition', 'string', ''),
        ('fastingFood', 'string', ''), ('fastingWater', 'string', ''),
        ('socialConditions', 'string', ''), ('immobilizationConditions', 'string', ''),
        ('operantConditioning', 'bool?', 'Whether trained behavior was used.'),
        ('environmentTemperature', 'amount', ''), ('waterTemperature', 'amount', ''), ('waterType', 'string', ''),
        ('gasAnestheticCircuit', 'string', ''), ('vitalsMonitor', 'string', ''),
        ('bpCuff', 'obj:BpCuff', ''),
        ('endotrachealTube', 'string', ''), ('endotrachealTubeComments', 'string', ''),
        ('inductionRating', 'rating', ''), ('recoveryRating', 'rating', ''), ('overallRating', 'rating', ''),
        ('restraintStartDateTime', 'dateTime', ''), ('initialEffectDateTime', 'dateTime', ''),
        ('recumbentDateTime', 'dateTime', ''), ('intubatedDateTime', 'dateTime', ''),
        ('extubatedDateTime', 'dateTime', ''), ('restraintEndDateTime', 'dateTime', ''),
        ('approvedDateTime', 'dateTime', ''),
        ('weightRef', 'ref', 'The `originRef` of the measurement set holding the weight used.'),
        ('estimatedWeightRef', 'ref', 'The same, for an estimated weight.'),
        ('monitoredTypes', 'strings', 'What was monitored, for example `Heart Rate`. The readings themselves are physiological readings with an `anesthesiaRef`.'),
        ('anesthetics', 'arr:Anesthetic', ''),
        ('catheters', 'arr:Catheter', ''),
        ('complications', 'arr:Complication', ''),
        ('effectObservations', 'arr:EffectObservation', ''),
        ('recoveryObservations', 'arr:RecoveryObservation', ''),
        ('summary', 'string', ''),
        ('comments', 'string', ''),
    ]),
    'BpCuff': ('', [('size', 'string', ''), ('location', 'string', '')]),
    'Anesthetic': ('', [
        ('givenDateTime', 'dateTime', ''),
        ('delivery', 'string', 'For example `Hand Syringe`, `Dart`.'),
        ('deliverySite', 'string', ''), ('injectionRoute', 'string', ''),
        ('needle', 'obj:Needle', ''),
        ('remoteDelivery', 'obj:RemoteDelivery', ''),
        ('animalWeight', 'amount', 'The weight the doses were calculated for.'),
        ('drugUse', 'arr:DrugUse', ''),
        ('comments', 'string', ''),
    ]),
    'Needle': ('', [('length', 'amount', ''), ('gauge', 'string', '')]),
    'RemoteDelivery': ('', [
        ('system', 'string', ''), ('dartType', 'string', ''), ('dartCharge', 'string', ''),
        ('powerSetting', 'string', ''), ('metersToAnimal', 'decimal', ''), ('percentDelivered', 'decimal', ''),
    ]),
    'Catheter': ('', [
        ('catheterType', 'string', ''), ('length', 'amount', ''), ('gauge', 'string', ''),
        ('location', 'string', ''), ('comments', 'string', ''),
    ]),
    'Complication': ('', [('complication*', 'string', ''), ('level', 'string', ''), ('comments', 'string', '')]),
    'EffectObservation': ('', [('recordDateTime', 'dateTime', ''), ('stage', 'string', '')]),
    'RecoveryObservation': ('', [('recordDateTime', 'dateTime', ''), ('stage', 'string', ''), ('comments', 'string', '')]),
    'LabCollection': ('A sample collection and the tests run on it.', [
        ('recordDateTime', 'dateTime', 'When the samples were collected.'),
        ('collectionReason', 'string', ''), ('fasting', 'string', ''), ('restraintType', 'string', ''),
        ('activityLevel', 'string', ''), ('healthStatus', 'string', ''),
        ('collectedBy', 'string', ''),
        ('comments', 'string', ''),
        ('samples', 'arr:LabSample', ''),
        ('animals', 'animals', ''),
    ]),
    'LabSample': ('', [
        ('sampleId', 'string', 'The source\'s sample identifier.'),
        ('sampleType', 'string', ''), ('sampleSite', 'string', ''),
        ('quantity', 'amount', ''),
        ('typical', 'bool?', 'Whether the sample is considered typical of the animal.'),
        ('storedOnly', 'boolean', '`true` when the sample was stored rather than tested.'),
        ('tests', 'arr:LabTest', ''),
    ]),
    'LabTest': ('', [
        ('lab', 'string', ''), ('testMethod', 'string', ''), ('labLocalId', 'string', 'The lab\'s own reference.'),
        ('currentStatus', 'string', 'The test\'s status as the source names it.'),
        ('statuses', 'arr:LabStatus', 'Each stage the test reached, in order.'),
        ('findings', 'arr:LabFinding', ''),
        ('textResults', 'string', ''), ('finalDiagnosis', 'string', ''), ('comments', 'string', ''),
    ]),
    'LabStatus': ('Not a record, so it carries no `originRef`.', [
        ('status*', 'token:requested|sentOut|resultsIn|approved', ''),
        ('by', 'string', ''),
        ('dateTime', 'dateTime', ''),
    ]),
    'LabFinding': ('', [
        ('finding*', 'string', 'What was measured, for example `WBC`.'),
        ('result', 'amount', 'The result. Its value may be text where the result is not a number, for example `1+`.'),
        ('reference', 'obj:Reference', 'The reference range the source holds for this finding and taxon.'),
    ]),
    'Reference': ('', [('mean', 'decimal', ''), ('low', 'decimal', ''), ('high', 'decimal', '')]),
    'Necropsy': ('A necropsy (post-mortem examination).', [
        ('necropsyNumber', 'string', ''), ('necropsyYear', 'string', ''),
        ('recordDate', 'date', 'When the necropsy was performed.'),
        ('deathTransactionRef', 'ref', 'The `originRef` of the death transaction.'),
        ('performedBy', 'string', ''),
        ('staff', 'people', 'Everyone involved, one person per entry.'),
        ('approvedDateTime', 'dateTime', ''),
        ('finalDiagnoses', 'strings', ''),
        ('noteText', 'text', 'The diagnosis and every findings section, each section under an `<h3>` heading.'),
        ('grossNecropsy', 'string', 'Gross findings recorded as a single text, where the source keeps one.'),
        ('histopathology', 'obj:Histopathology', ''),
        ('labTestRefs', 'refs', 'The `originRef`s of related lab tests.'),
        ('measurementRefs', 'refs', 'The `originRef`s of related measurement sets.'),
        ('media', 'files', ''),
    ]),
    'Histopathology': ('', [
        ('lab', 'string', ''), ('labNumber', 'string', ''), ('performedBy', 'string', ''),
        ('approvedDateTime', 'dateTime', ''),
        ('noteText', 'text', 'The diagnosis, comments and each section, under `<h3>` headings.'),
    ]),
    'DigitalImage': ('A radiograph, ultrasound or other diagnostic image study.', [
        ('recordDate', 'date', ''),
        ('description', 'string', ''), ('diagnosis', 'string', ''), ('comments', 'string', ''),
        ('slide', 'string', ''), ('fileNumber', 'string', ''), ('equipmentId', 'string', ''),
        ('otherId', 'string', ''), ('externalId', 'string', 'An identifier in an external imaging system.'),
        ('media', 'files', 'The image files.'),
    ]),

    # ---- husbandry ----
    'Measurements': ('Measurements: the animal\'s ranges, and the measurement sets.', [
        ('ranges', 'arr:MeasurementRange', 'The animal\'s acceptable and goal ranges.'),
        ('records', 'arr:MeasurementSet', 'The measurements, grouped in sets taken together.'),
    ]),
    'MeasurementRange': ('', [
        ('measureCode*', 'obj:MeasureCode', ''),
        ('startDate', 'date', 'When the range took effect.'),
        ('acceptable', 'range', ''),
        ('goal', 'range', ''),
        ('unit', 'string', 'The unit of both ranges.'),
        ('comments', 'string', ''),
    ]),
    'MeasureCode': ('', [
        ('description*', 'string', 'What is measured, for example `Weight`.'),
        ('unitType', 'string', 'The kind of unit, for example `Weight`, `Length`.'),
    ]),
    'MeasurementSet': ('', [
        ('recordDateTime', 'dateTime', ''),
        ('measurements', 'arr:Measurement', ''),
    ]),
    'Measurement': ('', [
        ('measureCode*', 'obj:MeasureCode', ''),
        ('quantity*', 'amount', ''),
        ('estimated', 'bool?', ''),
        ('method', 'string', ''),
        ('comments', 'string', ''),
    ]),
    'PhysiologicalReading': ('A set of physiological readings taken together.', [
        ('recordDateTime', 'dateTime', ''),
        ('anesthesiaRef', 'ref', 'The `originRef` of the anesthesia the readings were taken during, when they were.'),
        ('details', 'arr:PhysiologicalDetail', ''),
    ]),
    'PhysiologicalDetail': ('', [
        ('type*', 'string', 'For example `Heart Rate`.'),
        ('result', 'amount', ''),
    ]),
    'Contraception': ('A contraceptive method in use or used.', [
        ('recordDate', 'date', 'When it started.'),
        ('contraceptionType', 'string', ''),
        ('status', 'token:active|inactive', '`active` while it has no removal date.'),
        ('permanent', 'bool?', ''),
        ('removalDate', 'date', ''),
        ('removalComments', 'string', ''),
        ('comments', 'string', ''),
    ]),
    'Diet': ('A diet and its meals.', [
        ('name', 'string', ''),
        ('startDate', 'date', ''), ('endDate', 'date', ''),
        ('discontinuedReason', 'string', ''),
        ('fedIndividually', 'bool?', ''), ('batchDiet', 'bool?', ''),
        ('energyGoal', 'rate', 'The energy goal, for example 50 kcal per kg. `perUnit` is absent when the goal is a plain amount.'),
        ('comments', 'string', ''),
        ('meals', 'arr:Meal', ''),
        ('animals', 'animals', ''),
    ]),
    'Meal': ('', [
        ('name', 'string', ''),
        ('schedule', 'schedule', 'When the meal is fed.'),
        ('items', 'arr:MealItem', ''),
    ]),
    'MealItem': ('', [
        ('feedItem*', 'string', ''),
        ('quantity', 'amount', ''),
        ('unitEquivalent', 'amount', 'For a quantity in a custom unit, the size of one unit, for example 1 `Medium` = 40 g.'),
        ('feedingMethod', 'string', ''),
        ('description', 'string', ''),
    ]),
    'Feeding': ('What was offered and eaten at one feeding.', [
        ('recordDateTime', 'dateTime', ''),
        ('items', 'arr:FeedingItem', ''),
        ('appetite', 'string', ''),
        ('comments', 'string', ''),
        ('animals', 'animals', ''),
    ]),
    'FeedingItem': ('', [
        ('feedItem*', 'string', ''),
        ('offered', 'amount', ''), ('consumed', 'amount', ''),
        ('offeredEnergy', 'amount', ''), ('consumedEnergy', 'amount', ''),
        ('unitEquivalent', 'amount', ''),
        ('feedingMethod', 'string', ''), ('description', 'string', ''),
    ]),
    'Enrichment': ('Enrichment: the processes used, and the enrichment records.', [
        ('processes', 'arr:EnrichmentProcess', 'The enrichment processes the records refer to.'),
        ('records', 'arr:EnrichmentRecord', ''),
    ]),
    'EnrichmentProcess': ('', [
        ('name', 'string', 'The process\'s name.'),
        ('summary', 'string', 'A one-line description of the process (for example its status, taxa and goals) as the source composes it. Informative, for display only.'),
        ('goalRatingLabels', 'strings', 'The labels of the process\'s goal rating scale, in order.'),
        ('levelRatingLabels', 'strings', 'The labels of its level rating scale, in order.'),
    ]),
    'EnrichmentRecord': ('', [
        ('recordDateTime', 'dateTime', ''),
        ('processRef', 'ref', 'The `originRef` of the process.'),
        ('process', 'string', 'The process\'s name.'),
        ('levelRating', 'rating', ''),
        ('duration', 'amount', ''),
        ('foodUsed', 'bool?', ''), ('onExhibit', 'bool?', ''),
        ('recordedBy', 'string', ''),
        ('comments', 'string', ''),
        ('animals', 'animals', ''),
    ]),

    # ---- welfare and behavior ----
    'Observation': ('A behavioral or other observation.', [
        ('recordDateTime', 'dateTime', ''),
        ('observationType*', 'string', 'For example `Body Condition`.'),
        ('value', 'rating', 'The observed value and its label.'),
        ('observedBy', 'string', ''),
        ('duration', 'amount', ''),
        ('comments', 'string', ''),
        ('animals', 'animals', ''),
    ]),
    'WelfareAssessment': ('A welfare assessment and its answers.', [
        ('recordDateTime', 'dateTime', ''),
        ('protocol', 'string', 'The assessment protocol used.'),
        ('calculationMethod', 'string', 'How the overall score was calculated.'),
        ('score', 'decimal', 'The overall score.'),
        ('questions', 'arr:WelfareQuestion', 'Each question answered. A question left unanswered and without comment is omitted.'),
        ('animals', 'animals', ''),
    ]),
    'WelfareQuestion': ('Part of its assessment, so it carries no `originRef`.', [
        ('question*', 'string', ''),
        ('answer', 'rating', ''),
        ('comments', 'string', ''),
    ]),
    'ActionPlan': ('A welfare or management action plan.', [
        ('referenceNumber', 'string', ''),
        ('category', 'string', ''), ('priority', 'string', ''),
        ('status', 'token:unsubmitted|pending|approved|inProgress|completed|canceled', 'Where the plan stands.'),
        ('statusDate', 'date', ''), ('startDate', 'date', ''), ('completionDate', 'date', ''),
        ('reason', 'string', ''), ('description', 'string', ''),
        ('notes', 'arr:ActionPlanNote', 'The plan\'s log of comments.'),
        ('media', 'files', ''),
        ('animals', 'animals', ''),
    ]),
    'ActionPlanNote': ('', [
        ('noteText*', 'text', ''),
        ('automated', 'boolean', '`true` for an entry the source system wrote itself.'),
    ]),

    # ---- training ----
    'Training': ('Training: the behaviors, and the training sessions.', [
        ('behaviors', 'arr:TrainingBehavior', ''),
        ('records', 'arr:TrainingSession', 'The training sessions.'),
    ]),
    'TrainingBehavior': ('', [
        ('name*', 'string', ''),
        ('behaviorGoal', 'string', ''), ('approvalStatus', 'string', ''),
        ('audioCue', 'string', ''), ('visualCue', 'string', ''), ('tactileCue', 'string', ''),
        ('primaryReinforcement', 'string', ''),
        ('completedBehaviorDescription', 'string', ''),
        ('resources', 'string', ''),
        ('schedule', 'obj:TrainingSchedule', ''),
    ]),
    'TrainingSchedule': ('', [
        ('timePerSession', 'amount', ''),
        ('sessionsPerDay', 'decimal', ''),
        ('daysPerWeek', 'decimal', ''),
    ]),
    'TrainingSession': ('', [
        ('recordDateTime', 'dateTime', ''),
        ('sessionRating', 'rating', ''),
        ('duration', 'amount', ''),
        ('trainers', 'people', 'The trainers, one person per entry.'),
        ('comments', 'string', ''),
        ('sessionBehaviors', 'arr:SessionBehavior', ''),
        ('undesirableBehavior', 'obj:UndesirableBehavior', ''),
    ]),
    'SessionBehavior': ('', [
        ('behaviorRef', 'ref', 'The `originRef` of the behavior.'),
        ('behavior', 'string', 'The behavior\'s name.'),
        ('responseRating', 'rating', ''),
        ('progressToGoal', 'decimal', 'Percent.'),
        ('comments', 'string', ''),
    ]),
    'UndesirableBehavior': ('', [('description', 'string', ''), ('comments', 'string', '')]),

    # ---- media ----
    'Media': ('A file in the package.', [
        ('fileName*', 'string', 'The file\'s name in the package\'s `media/` folder, without the folder. Records refer to the file by this name.'),
        ('mediaType', 'string', 'The IANA media type, for example `image/jpeg`.'),
        ('sha256', 'sha256', 'The lowercase hexadecimal SHA-256 of the file; `null` when the writer could not include the file.'),
        ('description', 'string', ''),
        ('credits', 'string', ''),
        ('fileDateTime', 'dateTime', 'When the file was created or taken.'),
    ]),
}

# Record types, in the order the specification describes them, grouped as the site and viewer group them.
GROUPS = [
    ('Identity', [
        ('identifiers', 'arr', 'Identifier', 'Names, tags, transponders and other identifiers. The primary identifier is always shipped, even when the sender did not choose this type.'),
        ('parents', 'arr', 'Parent', 'The animal\'s parents.'),
        ('populations', 'arr', 'PopulationRecord', 'For a group or colony, the current count by life stage.'),
        ('rearings', 'arr', 'Rearing', 'How the animal was reared.'),
        ('sexHistory', 'arr', 'SexRecord', 'Sex determinations over time.'),
    ]),
    ('Medical', [
        ('anesthesias', 'arr', 'Anesthesia', 'Anesthesia and immobilization records.'),
        ('cases', 'arr', 'Case', 'Veterinary cases. Clinical notes refer to them with `caseRef`.'),
        ('chronicConditions', 'arr', 'ChronicCondition', 'Long-term conditions and their reviews.'),
        ('clinicalNotes', 'arr', 'ClinicalNote', 'Veterinary notes.'),
        ('digitalImaging', 'arr', 'DigitalImage', 'Radiographs and other diagnostic images.'),
        ('drugReactions', 'arr', 'DrugReaction', 'Adverse drug reactions.'),
        ('labCollections', 'arr', 'LabCollection', 'Sample collections, samples, tests and findings.'),
        ('medicalAlerts', 'arr', 'MedicalAlert', 'Alerts for people working with the animal.'),
        ('necropsies', 'arr', 'Necropsy', 'Post-mortem examinations.'),
        ('prescriptions', 'arr', 'Prescription', 'Prescriptions, drugs and doses.'),
    ]),
    ('Husbandry', [
        ('contraceptions', 'arr', 'Contraception', 'Contraception.'),
        ('diets', 'arr', 'Diet', 'Diets, meal by meal.'),
        ('enrichment', 'obj', 'Enrichment', 'Enrichment processes and records.'),
        ('feedings', 'arr', 'Feeding', 'Feeding records.'),
        ('measurements', 'obj', 'Measurements', 'Measurement ranges and measurements.'),
        ('nutritionNotes', 'arr', 'NutritionNote', 'Nutrition notes.'),
        ('physiologicalReadings', 'arr', 'PhysiologicalReading', 'Physiological readings such as heart rate.'),
    ]),
    ('Welfare and behavior', [
        ('actionPlans', 'arr', 'ActionPlan', 'Action plans.'),
        ('animalNotes', 'arr', 'AnimalNote', 'General notes about the animal.'),
        ('observations', 'arr', 'Observation', 'Observations.'),
        ('welfareAssessments', 'arr', 'WelfareAssessment', 'Welfare assessments.'),
    ]),
    ('Training', [
        ('training', 'obj', 'Training', 'Trained behaviors and training sessions.'),
    ]),
    ('Transaction history', [
        ('transactions', 'arr', 'Transaction', 'Acquisitions, dispositions, moves, births and deaths.'),
    ]),
    ('Media', [
        ('media', 'arr', 'Media', 'The files in the package.'),
    ]),
]

# Definitions needing at least one of several fields (in addition to any required ones).
ANY_OF = {
    'Core': [['localId'], ['gan']],
    'Drug': [['name'], ['genericName'], ['shortName']],
}

# Definitions that are not records (no originRef, recordedAt or audit).
NOT_RECORDS = {'Manifest', 'Software', 'ContentsRow', 'Core', 'Taxonomy', 'TaxonId', 'Birth', 'LifeCycle',
               'ParentId', 'TransactionType', 'Geo', 'Death', 'Rescue', 'Drug', 'Concentration', 'BpCuff',
               'Needle', 'RemoteDelivery', 'LabStatus', 'Reference', 'Histopathology', 'Measurements',
               'MeasureCode', 'Enrichment', 'Training', 'TrainingSchedule', 'UndesirableBehavior',
               'WelfareQuestion', 'PopulationRecord'}
